/** Sample notifications for My Account → Notifications tab. */
export const ACCOUNT_NOTIFICATIONS = [
  {
    id: 'n1',
    unread: true,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has added ', false],
      ['Play Football', true],
      [' to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '30 mins ago',
    bellMuted: false,
  },
  {
    id: 'n2',
    unread: true,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has removed ', false],
      ['Play Football', true],
      [' to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '3 hours ago',
    bellMuted: true,
  },
  {
    id: 'n3',
    unread: true,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has reordered ', false],
      ['Play Football', true],
      [' to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '5 hours ago',
    bellMuted: false,
  },
  {
    id: 'n4',
    unread: true,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has added ', false],
      ['Play Football Album', true],
      [' to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '6 hours ago',
    bellMuted: false,
  },
  {
    id: 'n5',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has commented on playlist ', false],
      ['NFL Soundtrack', true],
    ],
    timestamp: '10/24/20 4:10PM',
    bellMuted: false,
  },
  {
    id: 'n6',
    unread: false,
    initials: 'TR',
    parts: [
      ['Taylor Reed', true],
      [' has reordered ', false],
      ['Play Football Album', true],
      [' to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/24/20 4:10PM',
    bellMuted: false,
  },
  {
    id: 'n7',
    unread: false,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has added a comment to ', false],
      ['Play Football Album', true],
      [' to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/24/20 4:10PM',
    bellMuted: false,
  },
  {
    id: 'n8',
    unread: false,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has accepted an invitation to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/24/20 4:10PM',
    bellMuted: false,
  },
  {
    id: 'n9',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has removed you as an Editor from ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/24/20 4:10PM',
    bellMuted: false,
  },
  {
    id: 'n10',
    unread: false,
    initials: 'TR',
    parts: [
      ['Taylor Reed', true],
      [' has added you as an Editor from ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/24/20 4:10PM',
    bellMuted: false,
  },
  {
    id: 'n11',
    unread: true,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has shared ', false],
      ['Stadium Anthems', true],
      [' with you', false],
    ],
    timestamp: '8 hours ago',
    bellMuted: false,
  },
  {
    id: 'n12',
    unread: true,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has added ', false],
      ['Primetime Theme', true],
      [' to ', false],
      ['NFL Primetime', true],
    ],
    timestamp: '9 hours ago',
    bellMuted: false,
  },
  {
    id: 'n13',
    unread: true,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' mentioned you in ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '11 hours ago',
    bellMuted: true,
  },
  {
    id: 'n14',
    unread: true,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has uploaded ', false],
      ['Contemporary Italy', true],
      [' to ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '12 hours ago',
    bellMuted: false,
  },
  {
    id: 'n15',
    unread: true,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has invited you to collaborate on ', false],
      ['College Game Day', true],
    ],
    timestamp: '1 day ago',
    bellMuted: false,
  },
  {
    id: 'n16',
    unread: false,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has removed ', false],
      ['Touchdown Drive', true],
      [' from ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/23/20 2:15PM',
    bellMuted: false,
  },
  {
    id: 'n17',
    unread: false,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has commented on ', false],
      ['NFL Soundtrack', true],
    ],
    timestamp: '10/23/20 11:30AM',
    bellMuted: false,
  },
  {
    id: 'n18',
    unread: false,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has reordered ', false],
      ['Halftime Show', true],
      [' in ', false],
      ['Stadium Anthems', true],
    ],
    timestamp: '10/22/20 5:45PM',
    bellMuted: true,
  },
  {
    id: 'n19',
    unread: false,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has added you as a Viewer to ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '10/22/20 9:00AM',
    bellMuted: false,
  },
  {
    id: 'n20',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has accepted an invitation to ', false],
      ['Stadium Anthems', true],
    ],
    timestamp: '10/21/20 3:20PM',
    bellMuted: false,
  },
  {
    id: 'n21',
    unread: false,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has added ', false],
      ['Victory Lap', true],
      [' to ', false],
      ['NFL Primetime', true],
    ],
    timestamp: '10/21/20 10:05AM',
    bellMuted: false,
  },
  {
    id: 'n22',
    unread: false,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has removed you as an Editor from ', false],
      ['College Game Day', true],
    ],
    timestamp: '10/20/20 4:50PM',
    bellMuted: false,
  },
  {
    id: 'n23',
    unread: false,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has shared ', false],
      ['NFL Commercial', true],
      [' with you', false],
    ],
    timestamp: '10/20/20 1:30PM',
    bellMuted: false,
  },
  {
    id: 'n24',
    unread: false,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has added a comment to ', false],
      ['Contemporary Italy', true],
      [' in ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '10/19/20 6:15PM',
    bellMuted: true,
  },
  {
    id: 'n25',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has reordered ', false],
      ['Play Football', true],
      [' in ', false],
      ['NFL Soundtrack', true],
    ],
    timestamp: '10/19/20 8:40AM',
    bellMuted: false,
  },
  {
    id: 'n26',
    unread: false,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' mentioned you in ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/18/20 2:00PM',
    bellMuted: false,
  },
  {
    id: 'n27',
    unread: false,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has uploaded ', false],
      ['Opening Ceremony', true],
      [' to ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '10/17/20 11:55AM',
    bellMuted: false,
  },
  {
    id: 'n28',
    unread: false,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has added you as an Editor to ', false],
      ['Stadium Anthems', true],
    ],
    timestamp: '10/16/20 5:10PM',
    bellMuted: false,
  },
  {
    id: 'n29',
    unread: false,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has removed ', false],
      ['Primetime Theme', true],
      [' from ', false],
      ['NFL Primetime', true],
    ],
    timestamp: '10/15/20 9:25AM',
    bellMuted: false,
  },
  {
    id: 'n30',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has invited you to collaborate on ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '10/14/20 3:45PM',
    bellMuted: false,
  },
  {
    id: 'n31',
    unread: true,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has added ', false],
      ['Gold Medal Moment', true],
      [' to ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '2 days ago',
    bellMuted: false,
  },
  {
    id: 'n32',
    unread: true,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has commented on ', false],
      ['Stadium Anthems', true],
    ],
    timestamp: '2 days ago',
    bellMuted: true,
  },
  {
    id: 'n33',
    unread: true,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' mentioned you in ', false],
      ['NFL Primetime', true],
    ],
    timestamp: '3 days ago',
    bellMuted: false,
  },
  {
    id: 'n34',
    unread: true,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has shared ', false],
      ['College Game Day', true],
      [' with you', false],
    ],
    timestamp: '3 days ago',
    bellMuted: false,
  },
  {
    id: 'n35',
    unread: true,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has uploaded ', false],
      ['Postgame Wrap', true],
      [' to ', false],
      ['NFL Soundtrack', true],
    ],
    timestamp: '4 days ago',
    bellMuted: false,
  },
  {
    id: 'n36',
    unread: false,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has removed ', false],
      ['Victory Lap', true],
      [' from ', false],
      ['NFL Primetime', true],
    ],
    timestamp: '10/13/20 1:20PM',
    bellMuted: false,
  },
  {
    id: 'n37',
    unread: false,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has accepted an invitation to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/12/20 4:35PM',
    bellMuted: false,
  },
  {
    id: 'n38',
    unread: false,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has reordered ', false],
      ['Opening Ceremony', true],
      [' in ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '10/11/20 10:50AM',
    bellMuted: true,
  },
  {
    id: 'n39',
    unread: false,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has added a comment to ', false],
      ['Halftime Show', true],
      [' in ', false],
      ['Stadium Anthems', true],
    ],
    timestamp: '10/10/20 2:15PM',
    bellMuted: false,
  },
  {
    id: 'n40',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has added you as a Viewer to ', false],
      ['College Game Day', true],
    ],
    timestamp: '10/09/20 9:40AM',
    bellMuted: false,
  },
  {
    id: 'n41',
    unread: false,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has invited you to collaborate on ', false],
      ['NFL Soundtrack', true],
    ],
    timestamp: '10/08/20 6:05PM',
    bellMuted: false,
  },
  {
    id: 'n42',
    unread: false,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has removed you as an Editor from ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '10/07/20 11:30AM',
    bellMuted: false,
  },
  {
    id: 'n43',
    unread: false,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has added ', false],
      ['Kickoff Energy', true],
      [' to ', false],
      ['Stadium Anthems', true],
    ],
    timestamp: '10/06/20 3:55PM',
    bellMuted: false,
  },
  {
    id: 'n44',
    unread: false,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has shared ', false],
      ['NFL Primetime', true],
      [' with you', false],
    ],
    timestamp: '10/05/20 8:20AM',
    bellMuted: true,
  },
  {
    id: 'n45',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' mentioned you in ', false],
      ['College Game Day', true],
    ],
    timestamp: '10/04/20 5:45PM',
    bellMuted: false,
  },
  {
    id: 'n46',
    unread: false,
    initials: 'MR',
    parts: [
      ['Mark Ronson', true],
      [' has uploaded ', false],
      ['Contemporary Italy', true],
      [' to ', false],
      ['Winter Olympics 2026', true],
    ],
    timestamp: '10/03/20 12:10PM',
    bellMuted: false,
  },
  {
    id: 'n47',
    unread: false,
    initials: 'JL',
    parts: [
      ['Jessica Lee', true],
      [' has added you as an Editor to ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '10/02/20 4:25PM',
    bellMuted: false,
  },
  {
    id: 'n48',
    unread: false,
    initials: 'DK',
    parts: [
      ['David Kim', true],
      [' has commented on playlist ', false],
      ['NFL Soundtrack', true],
    ],
    timestamp: '10/01/20 9:15AM',
    bellMuted: false,
  },
  {
    id: 'n49',
    unread: false,
    initials: 'SR',
    parts: [
      ['Sara Ronson', true],
      [' has removed ', false],
      ['Touchdown Drive', true],
      [' from ', false],
      ['NFL Commercial', true],
    ],
    timestamp: '9/30/20 2:50PM',
    bellMuted: false,
  },
  {
    id: 'n50',
    unread: false,
    initials: 'AW',
    parts: [
      ['Alex Wong', true],
      [' has reordered ', false],
      ['Play Football Album', true],
      [' in ', false],
      ['NFL Soundtrack', true],
    ],
    timestamp: '9/29/20 7:30AM',
    bellMuted: false,
  },
];
