/**
 * Theme token registry — single source of truth for CSS custom property names and values.
 *
 * Usage:
 * - CSS: always prefer `var(--token-name)` from index.css `:root` / `[data-theme]`.
 * - JS: import CSS_VARS or THEME_PALETTES when a runtime color reference is required.
 *
 * When adding UI colors, add a token here first, define dark + light values in index.css,
 * then reference the variable in CSS/JS — never hardcode hex in components.
 */

export const THEME_STORAGE_KEY = 'apm-theme';
export const THEMES = ['dark', 'light'];
export const DEFAULT_THEME = 'dark';

/** Brand red — same in dark and light mode. Keep in sync with `--accent-red` in index.css. */
export const BRAND_RED = '#CC1E3C';
export const BRAND_RED_HOVER = '#b01a33';

/** Canonical CSS custom property names grouped by role. */
export const CSS_VARS = {
  bg: {
    chrome: '--bg-chrome',
    chromeMenu: '--bg-chrome-menu',
    sidebar: '--bg-sidebar',
    page: '--bg-page',
    dark: '--bg-dark',
    card: '--bg-card',
    elevated: '--bg-elevated',
    panel: '--bg-panel',
    nested: '--bg-nested',
    dropdown: '--bg-dropdown',
    search: '--bg-search',
  },
  surface: {
    default: '--surface-default',
    raised: '--surface-raised',
    muted: '--surface-muted',
    hover: '--surface-hover',
    selected: '--surface-selected',
  },
  text: {
    primary: '--text-primary',
    secondary: '--text-secondary',
    muted: '--text-muted',
    onChrome: '--text-on-chrome',
    onChromeMenu: '--text-on-chrome-menu',
    dropdown: '--text-dropdown',
    section: '--text-section',
    link: '--text-link',
    linkHover: '--text-link-hover',
  },
  border: {
    default: '--border',
    strong: '--border-strong',
    divider: '--border-divider',
    search: '--border-search',
    sidebar: '--border-sidebar',
  },
  accent: {
    red: '--accent-red',
    redHover: '--accent-red-hover',
    purple: '--accent-purple',
    purpleHover: '--accent-purple-hover',
    blue: '--accent-blue',
    blueHover: '--accent-blue-hover',
    soundsLike: '--accent-sounds-like',
    toggleOn: '--accent-toggle-on',
  },
  cta: {
    primaryBg: '--cta-primary-bg',
    primaryBgHover: '--cta-primary-bg-hover',
    secondaryBg: '--cta-secondary-bg',
    secondaryBgHover: '--cta-secondary-bg-hover',
    text: '--cta-text',
  },
  overlay: {
    hover: '--overlay-hover',
    hoverStrong: '--overlay-hover-strong',
    border: '--overlay-border',
    borderMedium: '--overlay-border-medium',
    shadow: '--shadow-dropdown',
  },
  control: {
    closeButton: '--control-close-bg',
    scrollbarThumb: '--scrollbar-thumb',
  },
  icon: {
    filter: '--icon-filter',
    filterMuted: '--icon-filter-muted',
    filterOnDarkSurface: '--icon-filter-on-dark-surface',
    filterNone: '--icon-filter-none',
  },
  account: {
    surface: '--account-surface',
    surfaceText: '--account-surface-text',
    surfaceTextMuted: '--account-surface-text-muted',
    surfaceBorder: '--account-surface-border',
    surfaceRadius: '--account-surface-radius',
  },
  profile: {
    amber: '--profile-amber',
    spring: '--profile-spring',
    cyan: '--profile-cyan',
    magenta: '--profile-magenta',
    rust: '--profile-rust',
    indigo: '--profile-indigo',
  },
};

/** Dark and light values for each token (design system + tooling). */
export const THEME_PALETTES = {
  dark: {
    '--bg-chrome': '#000000',
    '--bg-chrome-menu': '#000000',
    '--bg-sidebar': '#000000',
    '--bg-page': '#232323',
    '--bg-dark': '#0a0a0a',
    '--bg-card': '#141414',
    '--bg-elevated': '#1e1e1e',
    '--bg-panel': '#333333',
    '--bg-nested': '#262626',
    '--bg-dropdown': '#000000',
    '--bg-search': 'transparent',
    '--surface-default': '#303030',
    '--surface-raised': '#2e2e2e',
    '--surface-muted': '#343434',
    '--surface-hover': '#383838',
    '--surface-selected': '#1d415e',
    '--text-primary': '#ffffff',
    '--text-secondary': '#b0b0b0',
    '--text-muted': '#6b6b6b',
    '--text-on-chrome': '#ffffff',
    '--text-on-chrome-menu': '#ffffff',
    '--text-dropdown': '#ffffff',
    '--text-section': '#888888',
    '--text-link': '#7BBCEB',
    '--text-link-hover': '#6aa8d9',
    '--border': '#2a2a2a',
    '--border-strong': '#000000',
    '--border-divider': '#000000',
    '--border-search': '#ffffff',
    '--accent-red': BRAND_RED,
    '--accent-red-hover': BRAND_RED_HOVER,
    '--accent-purple': '#7c3aed',
    '--accent-purple-hover': '#6d28d9',
    '--accent-blue': '#3b82f6',
    '--accent-blue-hover': '#2563eb',
    '--accent-sounds-like': '#841FCC',
    '--accent-toggle-on': '#26d0d6',
    '--cta-secondary-bg': '#565656',
    '--cta-secondary-bg-hover': '#666666',
    '--cta-text': '#ffffff',
    '--overlay-hover': 'rgba(255, 255, 255, 0.08)',
    '--overlay-hover-strong': 'rgba(255, 255, 255, 0.1)',
    '--overlay-border': 'rgba(255, 255, 255, 0.15)',
    '--overlay-border-medium': 'rgba(255, 255, 255, 0.35)',
    '--shadow-dropdown': '0 12px 32px rgba(0, 0, 0, 0.45)',
    '--control-close-bg': '#565656',
    '--scrollbar-thumb': '#4d4d4d',
    '--account-surface': '#303030',
    '--account-surface-text': '#ffffff',
    '--account-surface-text-muted': '#9a9a9a',
    '--account-surface-border': '#000000',
    '--account-surface-radius': '8px',
    '--profile-amber': '#C17C2A',
    '--profile-spring': '#2BC174',
    '--profile-cyan': '#2AA3C1',
    '--profile-magenta': '#C12BC0',
    '--profile-rust': '#C12B2B',
    '--profile-indigo': '#3C2BC1',
    '--carousel-accent-fallback': '#3d3d3d',
    '--icon-filter': 'brightness(0) invert(1)',
    '--icon-filter-muted': 'brightness(0) invert(0.72)',
    '--icon-filter-on-dark-surface': 'brightness(0) invert(1)',
    '--icon-filter-none': 'none',
  },
  light: {
    '--bg-chrome': '#D9D9D9',
    '--bg-chrome-menu': '#D9D9D9',
    '--bg-sidebar': '#D9D9D9',
    '--bg-page': '#FFFFFF',
    '--bg-dark': '#FFFFFF',
    '--bg-card': '#FFFFFF',
    '--bg-elevated': '#FFFFFF',
    '--bg-panel': '#FFFFFF',
    '--bg-nested': '#F9F9F9',
    '--bg-dropdown': '#FFFFFF',
    '--bg-search': '#D9D9D9',
    '--surface-default': '#FFFFFF',
    '--surface-raised': '#FFFFFF',
    '--surface-muted': '#F9F9F9',
    '--surface-hover': '#F2F2F2',
    '--surface-selected': '#E6E6E6',
    '--text-primary': '#000000',
    '--text-secondary': '#4D4D4D',
    '--text-muted': '#808080',
    '--text-on-chrome': '#000000',
    '--text-on-chrome-menu': '#000000',
    '--text-dropdown': '#000000',
    '--text-section': '#4D4D4D',
    '--text-link': BRAND_RED,
    '--text-link-hover': BRAND_RED_HOVER,
    '--border': '#E0E0E0',
    '--border-strong': '#4D4D4D',
    '--border-divider': '#E0E0E0',
    '--border-search': '#4D4D4D',
    '--border-sidebar': '#B1B1B1',
    '--accent-red': BRAND_RED,
    '--accent-red-hover': BRAND_RED_HOVER,
    '--accent-purple': '#7c3aed',
    '--accent-purple-hover': '#6d28d9',
    '--accent-blue': '#3b82f6',
    '--accent-blue-hover': '#2563eb',
    '--accent-sounds-like': BRAND_RED,
    '--accent-toggle-on': '#26d0d6',
    '--cta-secondary-bg': '#565656',
    '--cta-secondary-bg-hover': '#666666',
    '--cta-text': '#FFFFFF',
    '--overlay-hover': 'rgba(0, 0, 0, 0.06)',
    '--overlay-hover-strong': 'rgba(0, 0, 0, 0.1)',
    '--overlay-border': 'rgba(0, 0, 0, 0.12)',
    '--overlay-border-medium': 'rgba(0, 0, 0, 0.25)',
    '--shadow-dropdown': '0 12px 32px rgba(0, 0, 0, 0.12)',
    '--control-close-bg': '#565656',
    '--scrollbar-thumb': '#B3B3B3',
    '--account-surface': '#efefef',
    '--account-surface-text': '#000000',
    '--account-surface-text-muted': '#808080',
    '--account-surface-border': '#E0E0E0',
    '--account-surface-radius': '8px',
    '--profile-amber': '#C17C2A',
    '--profile-spring': '#2BC174',
    '--profile-cyan': '#2AA3C1',
    '--profile-magenta': '#C12BC0',
    '--profile-rust': '#C12B2B',
    '--profile-indigo': '#3C2BC1',
    '--carousel-accent-fallback': '#E0E0E0',
    '--icon-filter': 'brightness(0)',
    '--icon-filter-muted': 'brightness(0)',
    '--icon-filter-on-dark-surface': 'brightness(0) invert(1)',
    '--icon-filter-none': 'none',
  },
};

export function themeVar(cssVar) {
  return `var(${cssVar})`;
}

export const THEME_TOKEN_GROUPS = Object.entries(CSS_VARS).map(([group, tokens]) => ({
  group,
  tokens: Object.entries(tokens).map(([name, cssVar]) => ({
    name,
    cssVar,
    dark: THEME_PALETTES.dark[cssVar],
    light: THEME_PALETTES.light[cssVar],
  })),
}));
